server:
  port: 9000

spring:
  application:
    name: tk-01-biz
  jackson:
    serialization:
      write-dates-as-timestamps: true

  datasource:
    primary:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/house?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      max-active: 8
      initial-size: 1

  servlet:
    multipart:
      enabled: false

logging:
  level:
    top.kwseeker.mybatis.tk: debug

#mybatis:
#  mapper-locations: classpath*:mapper/primary/*.xml
